### ISSUE TITLE
Evaluate the transition from az cli to Api in the Azure actions

### ISSUE THREAD

**Issue by kaverma** [Azure/actions#114]
We need to evaluate the feasibility, pros and cons of moving from az cli to API for login action and arm-deploy action. We also need to look at how the refresh logic will work with APIs the OIDC support being added.
Context - ARM Action incident - https://github.com/Azure/arm-deploy/discussions/69 

Outcome - Decide on the future path for Azure actions regarding cli vs Api.

**Comment by raiyanalam** [comment]
@kaverma - any update on this?

**Comment by kaverma** [comment]
As of now we haven't planned to move form cli to apis as there are challenges with token refresh while using apis, which is currently automatically being managed by cli. TO adress the problems related to breaks from cli, we are planning to add canary runs - https://github.com/Azure/actions/issues/122
So closing this issue
