### ISSUE TITLE
Failed to check app setting propagation

### ISSUE THREAD

**Issue by pjirsa** [Azure/actions#119]
Azure/functions-action@v1 to deploy my NodeJS Azure function.
Keep getting the following warnings:
- Warning: Failed to check app setting propagation for SCM_DO_BUILD_DURING_DEPLOYMENT, remaining retry 19
- Warning: Failed to check app setting propagation for ENABLE_ORYX_BUILD, remaining retry 19

Each one retries all the way to 0 with several seconds of delay between each one. This causes the deployment to take nearly 10 mins when it should only take a few seconds.

How can I avoid those warnings?

**Comment by sebastianrogers** [comment]
I am also seeing this issue

**Comment by BALAGA-GAYATRI** [comment]
Since your issue seems to be specific to [functions-action](https://github.com/Azure/functions-action), you will have to raise this issue there for appropriate response.
