### ISSUE TITLE
Add `Azure Load Testing` action to health-dashboard 

### ISSUE THREAD

**Issue by BALAGA-GAYATRI** [Azure/actions#127]
There are few steps to onboard any new action to [health-dashboard](https://azure.github.io/actions/health-dashboard.html). They include - 
1. creating a standard set of labels in your repository for incoming issues.
2. Adding Issue template.
3. Raise a PR in the actions repo.

The above steps 👆🏻 needs to be followed for [Azure load testing action](https://github.com/Azure/load-testing) to include in health-dashboard.

Please find the detailed process [here](https://github.com/Azure/actions/blob/main/docs/onboarding-to-dashboard.md#steps-to-follow-to-onboard-an-action-on-the-health-dashboard).

**Comment by ninallam** [comment]
Completed the above steps. Link to the PR https://github.com/Azure/actions/pull/128

**Comment by kaverma** [comment]
@BALAGA-GAYATRI , can we close this?
