### ISSUE TITLE
Set secret programmatically (REST API)

### ISSUE THREAD

**Issue by RoopeshNair** [Azure/actions#14]

**Comment by N-Usha** [comment]
Ask: “An API to set secrets to store Azure SPN/publishprofile details in GitHub. ”

This feature can be leveraged to create a great user experience for Azure customers from VS Code, cli and Azure Portal.

GitHub is informed of the ask but is yet to be prioritized.

**Comment by JasonFreeberg** [comment]
+1 on this

Being able to programmatically set secrets would be fantastic

**Comment by N-Usha** [comment]
This API is now available. Hence closing.
