### ISSUE TITLE
Authoring workflow: discover actions

### ISSUE THREAD

**Issue by RoopeshNair** [Azure/actions#15]

**Comment by N-Usha** [comment]
Issue : There is no easy way to discover Azure Actions in GitHub

•	Currently https://github.com/actions is one good place with a catalog of all the Actions. However the current entry for Azure is archived and redirects to https://github.com/Azure/actions which indexes all the Azure actions we shipped so far. 
•	Action “Edit workflow” experience if enhanced to show the Action/Templates catalog to the right of the authoring pane, could be great way to improve discoverability. But that enhancement should be owned by GitHub platform team.
•	https://github.com/marketplace/category/continuous-integration is another channel which we plan to leverage by creating a release for each of our actions and getting each an entry in Marketplace views.

**Comment by N-Usha** [comment]
Fixed  now with the new getting started improvements where there is a Marketplace search for Actions when you start editing an action workflow. However search for templates is still missing.
![image](https://user-images.githubusercontent.com/25389593/69527950-593cfe00-0f93-11ea-9f8f-9a7b5af785ae.png)
