### ISSUE TITLE
Starter CD template is restricted to only one per cloud and is not easily editable

### ISSUE THREAD

**Issue by N-Usha** [Azure/actions#32]
There is no provision to add a second hero template from Azure: Currently only 1 per cloud is allowed And for Azure, we chose it to be the template to deploy a Node app to Azure Web app. However we would also like to promote our AKS deploy template which now cant be done dure to this limitation.

cc @ethomson

![image](https://user-images.githubusercontent.com/25389593/69530130-87bcd800-0f97-11ea-8951-df1c3626f299.png)

**Comment by N-Usha** [comment]
Also it is not easy to edit a hero workflow without seeking help from GH team. it would have been easier if the templates are checked into some repo whose access is given to the template owners.

**Comment by ethomson** [comment]
You can open a pull request at https://github.com/actions/starter-workflows

**Comment by N-Usha** [comment]
Closing this as now we can edit templates by opening a PR in https://github.com/actions/starter-workflows
