### ISSUE TITLE
azure/k8s-deploy/v1 YAMLException

### ISSUE THREAD

**Issue by greenie-msft** [Azure/actions#48]
The azure/k8s-deploy/v1 action is resulting in an exception due to invalid YAML. Stack trace is below:

Error: YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 1, column 85:
     ... able. This is insecure. Location: /home/runner/work/_temp/kubeco ...
                                         ^

Has there been any changes to this action that would result in this error?

**Comment by ds-ms** [comment]
This issue seems to related to aks-set-context. Could you comment on the reported issue there with your findings?

**Comment by greenie-msft** [comment]
Absolutely. Thank you @ds-ms

**Comment by ds-ms** [comment]
Closing this duplicate issue; tracking it in the repo.
