### ISSUE TITLE
az login command should have the clientSecret masked

### ISSUE THREAD

**Issue by asw101** [Azure/actions#5]
When `az login --service-principal -u <clientId> -p <clientSecret> --tenant <tenantId>` is run in `Run azure/actions/login@master` the clientSecret is not masked and is visible in the logs.

I assume because this is not passed as its own, stand-alone, secret, despite the fact that using a single blob of JSON is extremely convenient.

**Comment by RoopeshNair** [comment]
We have fixed the issue now. We are in touch with the GitHub team and working with them to notify the affected users.

**Comment by RoopeshNair** [comment]
Resolved with the PR #7
