### ISSUE TITLE
GH Pages site is missing SVGs

### ISSUE THREAD

**Issue by isaacrlevin** [Azure/actions#70]
See screenshots 
![image](https://user-images.githubusercontent.com/8878502/118724311-4f403800-b7e3-11eb-96f1-f068b69b7946.png)

![image](https://user-images.githubusercontent.com/8878502/118724361-5d8e5400-b7e3-11eb-865c-0a6aeb24477a.png)

**Comment by N-Usha** [comment]
Thanks for reporting the issue @isaacrlevin. Closing the issue as it is now fixed: https://github.com/Azure/actions/pull/71
